name: Publish Docker image

on:
  push:
    branches: ['main']

jobs:
  build_and_push_image_to_docker_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps: 
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
            
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: captaingab/appimage:latest 
          
  ecr: 
    runs-on: ubuntu-latest
    needs: build_and_push_image_to_docker_registry
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change to your desired AWS region
        
      - name: Login to Amazon ECR
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 352566650999.dkr.ecr.us-east-1.amazonaws.com/vprofile-app-img
        
      - name: Pull Docker Image from Docker Hub
        run: docker pull captaingab/appimage:latest
      - name: Tag Docker Image for ECR
        run: docker tag your-dockerhub-username/your-image-name:latest your-account-id.dkr.ecr.us-east-1.amazonaws.com/your-image-name:latest

      - name: Push Docker Image to Amazon ECR
        run: docker push 352566650999.dkr.ecr.us-east-1.amazonaws.com/captaingab/appimage:latest