name: Publish Docker image

on:
  push:
    branches: ['main']

jobs:
  build_and_push_image_to_docker_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps: 
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
            
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: captaingab/appimage:latest 

                  
  build-and-push:
   runs-on: ubuntu-latest
   needs: build_and_push_image_to_docker_registry
   steps:
                - name: Checkout Repository
                  uses: actions/checkout@v2
          
                - name: Set up Docker Buildx
                  uses: docker/setup-buildx-action@v1

                - name: Configure AWS credentials
                  uses: aws-actions/configure-aws-credentials@v1
                  with:
                    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    aws-region: ${{secrets.AWS_REGION}}
          
                - name: Build Docker Image
                  run: |
                    docker build -t appimage:latest -f .
                    docker tag captaingab-appimage:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/vprofile-app-img:latest
                  env:
                    AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
                    AWS_REGION: ${{ secrets.AWS_REGION }}

                - name: Authenticate with ECR
                  run: |
                    aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
                  env:
                    AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
                    AWS_REGION: ${{ secrets.AWS_REGION }}
          
                - name: Push Docker Image to ECR
                  run: |
                    docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/vprofile-app-img:latest
                  env:
                    AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
                    AWS_REGION: ${{ secrets.AWS_REGION }}
          
     