name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

     
      - name: Build docker image
        run: docker build -t ${{ github.repository }}:${{ github.sha }} .
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push docker image to Docker Hub
        run: docker push ${{ github.repository }}:${{ github.sha }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Tag and push docker image to Amazon ECR
        run: |
          docker tag ${{ github.repository }}:${{ github.sha }} ${{ steps.login-ecr.outputs.registry }}/vprofile-app-img:${{ github.sha }}
          docker push ${{ steps.login-ecr.outputs.registry }}/vprofile-app-img:${{ github.sha }}

      - name: Deploy docker image to Amazon EKS
        uses: aws-actions/amazon-eks-kubectl-action@v1
        with:
          cluster-name: kubevpro.captaingab.online 
          role-arn: arn:aws:iam::352566650999:user/vprofile-kops-iam
          kubectl-command: set image deployment/deploymentservice.yml my-container=${{ steps.login-ecr.outputs.registry }}/vprofile-app-img:${{ github.sha }}
